version: '3'

services:
  database:
    image: 'postgres:latest'
    environment:
        POSTGRES_DB: products-api
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: banco123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
volumes:
  pgdata:

networks:
    mynetwork: